# 服务名
spring:
  application:
    name: eureka-client

# 服务端口号
server:
  port: 2001
# 注册中心的地址
eureka:
  instance:
    appname: eureka-client
  client:
    service-url:
      defaultZone: http://127.0.0.1:1001/eureka
    register-with-eureka: true
    fetch-registry: true

